name = "CESMIX"
uuid = "2199a845-376b-415c-8969-3466a94aa994"
repo = "git@github.com:cesmix-mit/CESMIX.git"
description = "The (temporary) registry for Julia packages developed by CESMIX"

[packages]
a963bdd2-2df7-4f54-a1ee-49d51e6be12a = { name = "AtomsBase", path = "A/AtomsBase" }
a9efe35a-c65d-452d-b8a8-82646cd5cb04 = { name = "InteratomicPotentials", path = "I/InteratomicPotentials" }
