name = "CESMIX"
uuid = "2199a845-376b-415c-8969-3466a94aa994"
repo = "git@github.com:cesmix-mit/CESMIX.git"
description = "The (temporary) registry for Julia packages developed by CESMIX"

[packages]
3e762ff9-b8d8-45cf-a902-edcbc7124e71 = { name = "Atomistic", path = "A/Atomistic" }
a9efe35a-c65d-452d-b8a8-82646cd5cb04 = { name = "InteratomicPotentials", path = "I/InteratomicPotentials" }
e3f9bc04-086e-409a-ba78-e9769fe067bb = { name = "ACE1", path = "A/ACE1" }
